/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedDeveloperIndexRouteImport } from './routes/_authenticated/developer/index'
import { Route as AuthenticatedAdminRolesIndexRouteImport } from './routes/_authenticated/admin-roles/index'
import { Route as AuthenticatedSystemAdminUsersRouteImport } from './routes/_authenticated/system/admin-users'
import { Route as AuthenticatedSystemAdminRolesRouteImport } from './routes/_authenticated/system/admin-roles'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDeveloperApiDocsRouteImport } from './routes/_authenticated/developer/api-docs'
import { Route as AuthenticatedDeveloperDemoIndexRouteImport } from './routes/_authenticated/developer/demo/index'
import { Route as AuthenticatedDeveloperDemoExcelRouteImport } from './routes/_authenticated/developer/demo/excel'
import { Route as AuthenticatedDeveloperDemoEditorRouteImport } from './routes/_authenticated/developer/demo/editor'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperIndexRoute =
  AuthenticatedDeveloperIndexRouteImport.update({
    id: '/developer/',
    path: '/developer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexRouteImport.update({
    id: '/admin-roles/',
    path: '/admin-roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemAdminUsersRoute =
  AuthenticatedSystemAdminUsersRouteImport.update({
    id: '/system/admin-users',
    path: '/system/admin-users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemAdminRolesRoute =
  AuthenticatedSystemAdminRolesRouteImport.update({
    id: '/system/admin-roles',
    path: '/system/admin-roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperApiDocsRoute =
  AuthenticatedDeveloperApiDocsRouteImport.update({
    id: '/developer/api-docs',
    path: '/developer/api-docs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperDemoIndexRoute =
  AuthenticatedDeveloperDemoIndexRouteImport.update({
    id: '/developer/demo/',
    path: '/developer/demo/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperDemoExcelRoute =
  AuthenticatedDeveloperDemoExcelRouteImport.update({
    id: '/developer/demo/excel',
    path: '/developer/demo/excel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperDemoEditorRoute =
  AuthenticatedDeveloperDemoEditorRouteImport.update({
    id: '/developer/demo/editor',
    path: '/developer/demo/editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer/api-docs': typeof AuthenticatedDeveloperApiDocsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/system/admin-roles': typeof AuthenticatedSystemAdminRolesRoute
  '/system/admin-users': typeof AuthenticatedSystemAdminUsersRoute
  '/admin-roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/developer/demo/editor': typeof AuthenticatedDeveloperDemoEditorRoute
  '/developer/demo/excel': typeof AuthenticatedDeveloperDemoExcelRoute
  '/developer/demo/': typeof AuthenticatedDeveloperDemoIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/developer/api-docs': typeof AuthenticatedDeveloperApiDocsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/system/admin-roles': typeof AuthenticatedSystemAdminRolesRoute
  '/system/admin-users': typeof AuthenticatedSystemAdminUsersRoute
  '/admin-roles': typeof AuthenticatedAdminRolesIndexRoute
  '/developer': typeof AuthenticatedDeveloperIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/developer/demo/editor': typeof AuthenticatedDeveloperDemoEditorRoute
  '/developer/demo/excel': typeof AuthenticatedDeveloperDemoExcelRoute
  '/developer/demo': typeof AuthenticatedDeveloperDemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/developer/api-docs': typeof AuthenticatedDeveloperApiDocsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/system/admin-roles': typeof AuthenticatedSystemAdminRolesRoute
  '/_authenticated/system/admin-users': typeof AuthenticatedSystemAdminUsersRoute
  '/_authenticated/admin-roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/developer/demo/editor': typeof AuthenticatedDeveloperDemoEditorRoute
  '/_authenticated/developer/demo/excel': typeof AuthenticatedDeveloperDemoExcelRoute
  '/_authenticated/developer/demo/': typeof AuthenticatedDeveloperDemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/developer/api-docs'
    | '/errors/$error'
    | '/system/admin-roles'
    | '/system/admin-users'
    | '/admin-roles/'
    | '/developer/'
    | '/users/'
    | '/developer/demo/editor'
    | '/developer/demo/excel'
    | '/developer/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/'
    | '/developer/api-docs'
    | '/errors/$error'
    | '/system/admin-roles'
    | '/system/admin-users'
    | '/admin-roles'
    | '/developer'
    | '/users'
    | '/developer/demo/editor'
    | '/developer/demo/excel'
    | '/developer/demo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/developer/api-docs'
    | '/_authenticated/errors/$error'
    | '/_authenticated/system/admin-roles'
    | '/_authenticated/system/admin-users'
    | '/_authenticated/admin-roles/'
    | '/_authenticated/developer/'
    | '/_authenticated/users/'
    | '/_authenticated/developer/demo/editor'
    | '/_authenticated/developer/demo/excel'
    | '/_authenticated/developer/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/': {
      id: '/_authenticated/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof AuthenticatedDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-roles/': {
      id: '/_authenticated/admin-roles/'
      path: '/admin-roles'
      fullPath: '/admin-roles/'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/admin-users': {
      id: '/_authenticated/system/admin-users'
      path: '/system/admin-users'
      fullPath: '/system/admin-users'
      preLoaderRoute: typeof AuthenticatedSystemAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/admin-roles': {
      id: '/_authenticated/system/admin-roles'
      path: '/system/admin-roles'
      fullPath: '/system/admin-roles'
      preLoaderRoute: typeof AuthenticatedSystemAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/api-docs': {
      id: '/_authenticated/developer/api-docs'
      path: '/developer/api-docs'
      fullPath: '/developer/api-docs'
      preLoaderRoute: typeof AuthenticatedDeveloperApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/demo/': {
      id: '/_authenticated/developer/demo/'
      path: '/developer/demo'
      fullPath: '/developer/demo/'
      preLoaderRoute: typeof AuthenticatedDeveloperDemoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/demo/excel': {
      id: '/_authenticated/developer/demo/excel'
      path: '/developer/demo/excel'
      fullPath: '/developer/demo/excel'
      preLoaderRoute: typeof AuthenticatedDeveloperDemoExcelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/demo/editor': {
      id: '/_authenticated/developer/demo/editor'
      path: '/developer/demo/editor'
      fullPath: '/developer/demo/editor'
      preLoaderRoute: typeof AuthenticatedDeveloperDemoEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDeveloperApiDocsRoute: typeof AuthenticatedDeveloperApiDocsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSystemAdminRolesRoute: typeof AuthenticatedSystemAdminRolesRoute
  AuthenticatedSystemAdminUsersRoute: typeof AuthenticatedSystemAdminUsersRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedDeveloperIndexRoute: typeof AuthenticatedDeveloperIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedDeveloperDemoEditorRoute: typeof AuthenticatedDeveloperDemoEditorRoute
  AuthenticatedDeveloperDemoExcelRoute: typeof AuthenticatedDeveloperDemoExcelRoute
  AuthenticatedDeveloperDemoIndexRoute: typeof AuthenticatedDeveloperDemoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDeveloperApiDocsRoute: AuthenticatedDeveloperApiDocsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSystemAdminRolesRoute: AuthenticatedSystemAdminRolesRoute,
  AuthenticatedSystemAdminUsersRoute: AuthenticatedSystemAdminUsersRoute,
  AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
  AuthenticatedDeveloperIndexRoute: AuthenticatedDeveloperIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedDeveloperDemoEditorRoute: AuthenticatedDeveloperDemoEditorRoute,
  AuthenticatedDeveloperDemoExcelRoute: AuthenticatedDeveloperDemoExcelRoute,
  AuthenticatedDeveloperDemoIndexRoute: AuthenticatedDeveloperDemoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
